[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testfooproj"
version = "0.0.22"
description = "TEST"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "aletgn"}]
license = "MIT"
keywords = ["test", "example", "python"]

[project.urls]
Homepage = "https://github.com/aletgn/test-foo-project"
Repository = "https://github.com/aletgn/test-foo-project"
Documentation = "https://github.com/aletgn/test-foo-project#readme"

[project.optional-dependencies]
test = ["notebook"]
dev = ["pytest", "twine", "setuptools", "build"]

[tool.setuptools.packages.find]
where = ["src"]
